version: '3.4'

services:
  webapi:
    image: ${DOCKER_REGISTRY}/studentachieve-webapi:${TAG:-latest}
    build:
      context: .
      dockerfile: src/Student.Achieve.WebApi/Dockerfile
    volumes: 
      - wwwroot:/app/wwwroot:rw
      - logs:/app/logs:rw

volumes: 
  logs:
    external: false
  wwwroot:
    external: false